//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsteoYoga.Resource.Holiday {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HolidayResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HolidayResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OsteoYoga.Resource.Holiday.HolidayResource", typeof(HolidayResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a des rendez-vous à cette date. Veuillez en premier lieu les annuler..
        /// </summary>
        public static string DateTakenAtThisDate {
            get {
                return ResourceManager.GetString("DateTakenAtThisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le congé a été annulé..
        /// </summary>
        public static string HolidayCancelled {
            get {
                return ResourceManager.GetString("HolidayCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacances.
        /// </summary>
        public static string Holidays {
            get {
                return ResourceManager.GetString("Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le congé a été pris..
        /// </summary>
        public static string HolidayTaken {
            get {
                return ResourceManager.GetString("HolidayTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prendre un congé au :.
        /// </summary>
        public static string TakeAnHolidayAtThe {
            get {
                return ResourceManager.GetString("TakeAnHolidayAtThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prendre le congé à cette date..
        /// </summary>
        public static string TakeTheHoliday {
            get {
                return ResourceManager.GetString("TakeTheHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  à .
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
    }
}
