//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsteoYoga.Resource.RendezVous {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DateResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DateResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OsteoYoga.Resource.RendezVous.DateResource", typeof(DateResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toute la journée.
        /// </summary>
        public static string AllTheDay {
            get {
                return ResourceManager.GetString("AllTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le matin.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez sélectionner au moins une date de disponibilité..
        /// </summary>
        public static string AtLeastOnePatientHour {
            get {
                return ResourceManager.GetString("AtLeastOnePatientHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez sélectionner que cinq plages horaires maximum..
        /// </summary>
        public static string AtMaxFivePatientHours {
            get {
                return ResourceManager.GetString("AtMaxFivePatientHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un rendez-vous peut-être pris.
        /// </summary>
        public static string DateMayBeTaken {
            get {
                return ResourceManager.GetString("DateMayBeTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre demande de rendez-vous a bien été prise en compte..
        /// </summary>
        public static string DatePropose {
            get {
                return ResourceManager.GetString("DatePropose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande de rendez-vous.
        /// </summary>
        public static string DateQuery {
            get {
                return ResourceManager.GetString("DateQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Sélectionnez une date..
        /// </summary>
        public static string DateSelection {
            get {
                return ResourceManager.GetString("DateSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre demande de rendez-vous a bien été validée..
        /// </summary>
        public static string DateValidated {
            get {
                return ResourceManager.GetString("DateValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous venez de recevoir un e-mail vous demandant de confirmer ce rendez vous. Veuillez suivre le lien qui y est indiqué..
        /// </summary>
        public static string EmailSending {
            get {
                return ResourceManager.GetString("EmailSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est produite. Veuillez appeler directement M. Nicolas Truffart pour prendre rendez-vous..
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a eu une erreur. Veuillez contacter Nicolas Truffart..
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;y a plus de place disponible dans les créneaux horaires indiqués.
        /// </summary>
        public static string NoFreeTimeSlot {
            get {
                return ResourceManager.GetString("NoFreeTimeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;après-midi.
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prendre le rendez-vous.
        /// </summary>
        public static string TakeTheDate {
            get {
                return ResourceManager.GetString("TakeTheDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Sélectionnez une tranche de disponibilité..
        /// </summary>
        public static string TimeSlotSelection {
            get {
                return ResourceManager.GetString("TimeSlotSelection", resourceCulture);
            }
        }
    }
}
