//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsteoYoga.Resource.RendezVous {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DateResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DateResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OsteoYoga.Resource.RendezVous.DateResource", typeof(DateResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toute la journée.
        /// </summary>
        public static string AllTheDay {
            get {
                return ResourceManager.GetString("AllTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le matin.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez sélectionner au moins une date de disponibilité..
        /// </summary>
        public static string AtLeastOnePatientHour {
            get {
                return ResourceManager.GetString("AtLeastOnePatientHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez sélectionner que cinq plages horaires maximum..
        /// </summary>
        public static string AtMaxFivePatientHours {
            get {
                return ResourceManager.GetString("AtMaxFivePatientHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un rendez-vous peut-être pris.
        /// </summary>
        public static string DateMayBeTaken {
            get {
                return ResourceManager.GetString("DateMayBeTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre demande de rendez-vous a bien été prise en compte..
        /// </summary>
        public static string DatePropose {
            get {
                return ResourceManager.GetString("DatePropose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande de rendez-vous.
        /// </summary>
        public static string DateQuery {
            get {
                return ResourceManager.GetString("DateQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. Sélectionnez une date..
        /// </summary>
        public static string DateSelection {
            get {
                return ResourceManager.GetString("DateSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre demande de rendez-vous a bien été validée..
        /// </summary>
        public static string DateValidated {
            get {
                return ResourceManager.GetString("DateValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous venez de recevoir un e-mail vous demandant de confirmer ce rendez vous. Veuillez suivre le lien qui y est indiqué..
        /// </summary>
        public static string EmailSending {
            get {
                return ResourceManager.GetString("EmailSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite. Veuillez appeler directement M. Nicolas Truffart pour prendre rendez-vous..
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il y a eu une erreur. Veuillez contacter Nicolas Truffart..
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il n&apos;y a plus de place disponible dans les créneaux horaires indiqués.
        /// </summary>
        public static string NoFreeTimeSlot {
            get {
                return ResourceManager.GetString("NoFreeTimeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Office_Name_Name {
            get {
                return ResourceManager.GetString("Office_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez un cabinet.
        /// </summary>
        public static string OfficeList {
            get {
                return ResourceManager.GetString("OfficeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;après-midi.
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prendre le rendez-vous.
        /// </summary>
        public static string TakeTheDate {
            get {
                return ResourceManager.GetString("TakeTheDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Sélectionnez une tranche de disponibilité..
        /// </summary>
        public static string TimeSlotSelection {
            get {
                return ResourceManager.GetString("TimeSlotSelection", resourceCulture);
            }
        }
    }
}
